// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: TestService.proto

package org.example.rpc;

public interface ApiInOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ApiIn)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string name = 1;</code>
   * @return The name.
   */
  java.lang.String getName();
  /**
   * <code>string name = 1;</code>
   * @return The bytes for name.
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <code>string code = 2;</code>
   * @return The code.
   */
  java.lang.String getCode();
  /**
   * <code>string code = 2;</code>
   * @return The bytes for code.
   */
  com.google.protobuf.ByteString
      getCodeBytes();

  /**
   * <code>int64 age = 3;</code>
   * @return The age.
   */
  long getAge();
}
