// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: TestService.proto

package org.example.rpc;

public interface ApiOutOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ApiOut)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bool success = 1;</code>
   * @return The success.
   */
  boolean getSuccess();

  /**
   * <code>string auth = 2;</code>
   * @return The auth.
   */
  java.lang.String getAuth();
  /**
   * <code>string auth = 2;</code>
   * @return The bytes for auth.
   */
  com.google.protobuf.ByteString
      getAuthBytes();
}
