// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: TestService.proto

package org.example.rpc;

public final class TestServiceOuterClass {
  private TestServiceOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ApiIn_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ApiIn_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ApiOut_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ApiOut_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\021TestService.proto\"0\n\005ApiIn\022\014\n\004name\030\001 \001" +
      "(\t\022\014\n\004code\030\002 \001(\t\022\013\n\003age\030\003 \001(\003\"\'\n\006ApiOut\022" +
      "\017\n\007success\030\001 \001(\010\022\014\n\004auth\030\002 \001(\t2-\n\013TestSe" +
      "rvice\022\036\n\tCheckUser\022\006.ApiIn\032\007.ApiOut\"\000B\023\n" +
      "\017org.example.rpcP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_ApiIn_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_ApiIn_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ApiIn_descriptor,
        new java.lang.String[] { "Name", "Code", "Age", });
    internal_static_ApiOut_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_ApiOut_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ApiOut_descriptor,
        new java.lang.String[] { "Success", "Auth", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
